const size = 15;

export const defaultGrid = () => {
  const grid = [];
  for (let i = 0; i < size; i++) {
    const row = [];
    for (let j = 0; j < size; j++) {
      const cell = { id: `${i}_${j}`, value: '.', color: '' };
      row.push(cell);
    }
    grid.push(row);
  }
  return grid;
};

export const defaults = {
  grid: defaultGrid(),
  width: size,
  height: size,
  scale: 15,
  color: {
    id: '1_1',
    value: '1',
    color: '#9d9d9d',
  },
  contrast: true,
};

export const initialGrid = () => {
  return [
    [
      { id: '0_0', value: '.', color: '' },
      { id: '0_1', value: '.', color: '' },
      { id: '0_2', value: '.', color: '' },
      { id: '0_3', value: '.', color: '' },
      { id: '0_4', value: '.', color: '' },
      { id: '0_5', value: '.', color: '' },
      { id: '0_6', value: '.', color: '' },
      { id: '0_7', value: '.', color: '' },
      { id: '0_8', value: '.', color: '' },
      { id: '0_9', value: '.', color: '' },
      { id: '0_10', value: '.', color: '' },
      { id: '0_11', value: '.', color: '' },
      { id: '0_12', value: '.', color: '' },
      { id: '0_13', value: '.', color: '' },
      { id: '0_14', value: '.', color: '' },
    ],
    [
      { id: '1_0', value: '.', color: '' },
      { id: '1_1', value: '.', color: '' },
      { id: '1_2', value: '.', color: '' },
      { id: '1_3', value: 'A', color: '#44891a' },
      { id: '1_4', value: 'A', color: '#44891a' },
      { id: '1_5', value: 'A', color: '#44891a' },
      { id: '1_6', value: 'A', color: '#44891a' },
      { id: '1_7', value: '.', color: '' },
      { id: '1_8', value: 'A', color: '#44891a' },
      { id: '1_9', value: 'A', color: '#44891a' },
      { id: '1_10', value: 'A', color: '#44891a' },
      { id: '1_11', value: 'A', color: '#44891a' },
      { id: '1_12', value: '.', color: '' },
      { id: '1_13', value: '.', color: '' },
      { id: '1_14', value: '.', color: '' },
    ],
    [
      { id: '2_0', value: '.', color: '' },
      { id: '2_1', value: '.', color: '' },
      { id: '2_2', value: '.', color: '' },
      { id: '2_3', value: 'A', color: '#44891a' },
      { id: '2_4', value: 5, color: '#493c2b' },
      { id: '2_5', value: 2, color: '#ffffff' },
      { id: '2_6', value: 'A', color: '#44891a' },
      { id: '2_7', value: 'A', color: '#44891a' },
      { id: '2_8', value: 'A', color: '#44891a' },
      { id: '2_9', value: 5, color: '#493c2b' },
      { id: '2_10', value: 2, color: '#ffffff' },
      { id: '2_11', value: 'A', color: '#44891a' },
      { id: '2_12', value: '.', color: '' },
      { id: '2_13', value: '.', color: '' },
      { id: '2_14', value: '.', color: '' },
    ],
    [
      { id: '3_0', value: '.', color: '' },
      { id: '3_1', value: '.', color: '' },
      { id: '3_2', value: 'A', color: '#44891a' },
      { id: '3_3', value: 'B', color: '#a3ce27' },
      { id: '3_4', value: 5, color: '#493c2b' },
      { id: '3_5', value: 5, color: '#493c2b' },
      { id: '3_6', value: 'B', color: '#a3ce27' },
      { id: '3_7', value: 'B', color: '#a3ce27' },
      { id: '3_8', value: 'B', color: '#a3ce27' },
      { id: '3_9', value: 5, color: '#493c2b' },
      { id: '3_10', value: 5, color: '#493c2b' },
      { id: '3_11', value: 'B', color: '#a3ce27' },
      { id: '3_12', value: 'A', color: '#44891a' },
      { id: '3_13', value: '.', color: '' },
      { id: '3_14', value: '.', color: '' },
    ],
    [
      { id: '4_0', value: '.', color: '' },
      { id: '4_1', value: '.', color: '' },
      { id: '4_2', value: 'A', color: '#44891a' },
      { id: '4_3', value: 'B', color: '#a3ce27' },
      { id: '4_4', value: 'B', color: '#a3ce27' },
      { id: '4_5', value: 'B', color: '#a3ce27' },
      { id: '4_6', value: 'B', color: '#a3ce27' },
      { id: '4_7', value: 'B', color: '#a3ce27' },
      { id: '4_8', value: 'B', color: '#a3ce27' },
      { id: '4_9', value: 'B', color: '#a3ce27' },
      { id: '4_10', value: 'B', color: '#a3ce27' },
      { id: '4_11', value: 'B', color: '#a3ce27' },
      { id: '4_12', value: 'A', color: '#44891a' },
      { id: '4_13', value: '.', color: '' },
      { id: '4_14', value: '.', color: '' },
    ],
    [
      { id: '5_0', value: '.', color: '' },
      { id: '5_1', value: '.', color: '' },
      { id: '5_2', value: 'A', color: '#44891a' },
      { id: '5_3', value: 'B', color: '#a3ce27' },
      { id: '5_4', value: 'B', color: '#a3ce27' },
      { id: '5_5', value: 'B', color: '#a3ce27' },
      { id: '5_6', value: 5, color: '#493c2b' },
      { id: '5_7', value: 5, color: '#493c2b' },
      { id: '5_8', value: 5, color: '#493c2b' },
      { id: '5_9', value: 'B', color: '#a3ce27' },
      { id: '5_10', value: 'B', color: '#a3ce27' },
      { id: '5_11', value: 'B', color: '#a3ce27' },
      { id: '5_12', value: 'A', color: '#44891a' },
      { id: '5_13', value: '.', color: '' },
      { id: '5_14', value: '.', color: '' },
    ],
    [
      { id: '6_0', value: '.', color: '' },
      { id: '6_1', value: '.', color: '' },
      { id: '6_2', value: '.', color: '' },
      { id: '6_3', value: 'A', color: '#44891a' },
      { id: '6_4', value: 'A', color: '#44891a' },
      { id: '6_5', value: 'B', color: '#a3ce27' },
      { id: '6_6', value: 'B', color: '#a3ce27' },
      { id: '6_7', value: 'B', color: '#a3ce27' },
      { id: '6_8', value: 'B', color: '#a3ce27' },
      { id: '6_9', value: 'B', color: '#a3ce27' },
      { id: '6_10', value: 'A', color: '#44891a' },
      { id: '6_11', value: 'A', color: '#44891a' },
      { id: '6_12', value: '.', color: '' },
      { id: '6_13', value: '.', color: '' },
      { id: '6_14', value: '.', color: '' },
    ],
    [
      { id: '7_0', value: '.', color: '' },
      { id: '7_1', value: '.', color: '' },
      { id: '7_2', value: '.', color: '' },
      { id: '7_3', value: '.', color: '' },
      { id: '7_4', value: '.', color: '' },
      { id: '7_5', value: 'A', color: '#44891a' },
      { id: '7_6', value: 'B', color: '#a3ce27' },
      { id: '7_7', value: 'B', color: '#a3ce27' },
      { id: '7_8', value: 'B', color: '#a3ce27' },
      { id: '7_9', value: 'A', color: '#44891a' },
      { id: '7_10', value: '.', color: '' },
      { id: '7_11', value: '.', color: '' },
      { id: '7_12', value: '.', color: '' },
      { id: '7_13', value: '.', color: '' },
      { id: '7_14', value: '.', color: '' },
    ],
    [
      { id: '8_0', value: '.', color: '' },
      { id: '8_1', value: '.', color: '' },
      { id: '8_2', value: '.', color: '' },
      { id: '8_3', value: '.', color: '' },
      { id: '8_4', value: 'A', color: '#44891a' },
      { id: '8_5', value: 'B', color: '#a3ce27' },
      { id: '8_6', value: 'B', color: '#a3ce27' },
      { id: '8_7', value: 'B', color: '#a3ce27' },
      { id: '8_8', value: 'B', color: '#a3ce27' },
      { id: '8_9', value: 'B', color: '#a3ce27' },
      { id: '8_10', value: 'A', color: '#44891a' },
      { id: '8_11', value: '.', color: '' },
      { id: '8_12', value: '.', color: '' },
      { id: '8_13', value: '.', color: '' },
      { id: '8_14', value: '.', color: '' },
    ],
    [
      { id: '9_0', value: '.', color: '' },
      { id: '9_1', value: '.', color: '' },
      { id: '9_2', value: '.', color: '' },
      { id: '9_3', value: 'A', color: '#44891a' },
      { id: '9_4', value: 'B', color: '#a3ce27' },
      { id: '9_5', value: 'B', color: '#a3ce27' },
      { id: '9_6', value: 'B', color: '#a3ce27' },
      { id: '9_7', value: 'A', color: '#44891a' },
      { id: '9_8', value: 'B', color: '#a3ce27' },
      { id: '9_9', value: 'B', color: '#a3ce27' },
      { id: '9_10', value: 'B', color: '#a3ce27' },
      { id: '9_11', value: 'A', color: '#44891a' },
      { id: '9_12', value: '.', color: '' },
      { id: '9_13', value: '.', color: '' },
      { id: '9_14', value: '.', color: '' },
    ],
    [
      { id: '10_0', value: '.', color: '' },
      { id: '10_1', value: '.', color: '' },
      { id: '10_2', value: 'A', color: '#44891a' },
      { id: '10_3', value: 'A', color: '#44891a' },
      { id: '10_4', value: 'B', color: '#a3ce27' },
      { id: '10_5', value: 'A', color: '#44891a' },
      { id: '10_6', value: 'B', color: '#a3ce27' },
      { id: '10_7', value: 'B', color: '#a3ce27' },
      { id: '10_8', value: 'B', color: '#a3ce27' },
      { id: '10_9', value: 'A', color: '#44891a' },
      { id: '10_10', value: 'B', color: '#a3ce27' },
      { id: '10_11', value: 'A', color: '#44891a' },
      { id: '10_12', value: 'A', color: '#44891a' },
      { id: '10_13', value: '.', color: '' },
      { id: '10_14', value: '.', color: '' },
    ],
    [
      { id: '11_0', value: '.', color: '' },
      { id: '11_1', value: '.', color: '' },
      { id: '11_2', value: '.', color: '' },
      { id: '11_3', value: 'A', color: '#44891a' },
      { id: '11_4', value: 'B', color: '#a3ce27' },
      { id: '11_5', value: 'B', color: '#a3ce27' },
      { id: '11_6', value: 'A', color: '#44891a' },
      { id: '11_7', value: 'A', color: '#44891a' },
      { id: '11_8', value: 'A', color: '#44891a' },
      { id: '11_9', value: 'B', color: '#a3ce27' },
      { id: '11_10', value: 'B', color: '#a3ce27' },
      { id: '11_11', value: 'A', color: '#44891a' },
      { id: '11_12', value: '.', color: '' },
      { id: '11_13', value: '.', color: '' },
      { id: '11_14', value: '.', color: '' },
    ],
    [
      { id: '12_0', value: '.', color: '' },
      { id: '12_1', value: '.', color: '' },
      { id: '12_2', value: '.', color: '' },
      { id: '12_3', value: '.', color: '' },
      { id: '12_4', value: 'A', color: '#44891a' },
      { id: '12_5', value: 'A', color: '#44891a' },
      { id: '12_6', value: 'A', color: '#44891a' },
      { id: '12_7', value: '.', color: '' },
      { id: '12_8', value: 'A', color: '#44891a' },
      { id: '12_9', value: 'A', color: '#44891a' },
      { id: '12_10', value: 'A', color: '#44891a' },
      { id: '12_11', value: '.', color: '' },
      { id: '12_12', value: '.', color: '' },
      { id: '12_13', value: '.', color: '' },
      { id: '12_14', value: '.', color: '' },
    ],
    [
      { id: '13_0', value: '.', color: '' },
      { id: '13_1', value: '.', color: '' },
      { id: '13_2', value: '.', color: '' },
      { id: '13_3', value: 'A', color: '#44891a' },
      { id: '13_4', value: 'A', color: '#44891a' },
      { id: '13_5', value: 'B', color: '#a3ce27' },
      { id: '13_6', value: 'A', color: '#44891a' },
      { id: '13_7', value: '.', color: '' },
      { id: '13_8', value: 'A', color: '#44891a' },
      { id: '13_9', value: 'B', color: '#a3ce27' },
      { id: '13_10', value: 'A', color: '#44891a' },
      { id: '13_11', value: 'A', color: '#44891a' },
      { id: '13_12', value: '.', color: '' },
      { id: '13_13', value: '.', color: '' },
      { id: '13_14', value: '.', color: '' },
    ],
    [
      { id: '14_0', value: '.', color: '' },
      { id: '14_1', value: '.', color: '' },
      { id: '14_2', value: '.', color: '' },
      { id: '14_3', value: '.', color: '' },
      { id: '14_4', value: '.', color: '' },
      { id: '14_5', value: '.', color: '' },
      { id: '14_6', value: '.', color: '' },
      { id: '14_7', value: '.', color: '' },
      { id: '14_8', value: '.', color: '' },
      { id: '14_9', value: '.', color: '' },
      { id: '14_10', value: '.', color: '' },
      { id: '14_11', value: '.', color: '' },
      { id: '14_12', value: '.', color: '' },
      { id: '14_13', value: '.', color: '' },
      { id: '14_14', value: '.', color: '' },
    ],
  ];
};
